# docker-compose.yml



services:
  ollama:
    image: ollama/ollama:latest
    restart: unless-stopped
    volumes:
      - ollama-data:/root/.ollama
    ports:
      - "11434:11434"
    networks:
      - geosearchqa-network

  geosearchqa:
    build: .
    restart: unless-stopped
    env_file:
      - .env
    depends_on:
      - ollama
    ports:
      - "8000:8000"
    environment:
      - OLLAMA_BASE_URL=http://ollama:11434
      - MODEL_NAME=llama3:8b
      - BRAVE_API_KEY=${BRAVE_API_KEY}
      - MCP_ENABLED=true
      - MCP_VERSION=1.0
    networks:
      - geosearchqa-network

networks:
  geosearchqa-network:
    driver: bridge

volumes:
  ollama-data: